### ISSUE TITLE
Feature/Bug Tracker

### ISSUE THREAD

**Issue by Carlosted** [Carlosted/icondata#37]
Here is a table of missing features and bugs for this crate. Please do try your hand at any of the tasks listed below if you feel like it would improve your developer experience!

- [ ] RAM usage issue with `rust-analyzer`.
    I have not found a way to configure `rust-analyzer` so that it does not import into memory every icon's name, even when the library is not imported. `icondata` seems to take around 700MB of RAM on my machine with `rust-analyzer`.  I'm not highly knowledgeable about `rust-analyzer`'s infrastructure, but I believe it would require us to file an issue to `rust-analyzer` to add configuration options for our use case.
- [ ] Explorer site not working on small screens.
    This issue is a simple task, it only requires making a dynamic header with tailwind.
- [ ] Most icons from HeroIcons are not rendering.
- [ ] Writing a cron job that periodically updates icon libraries.
- [ ] What should we do with icon categories e.g., Sm, Md, Lg, etc.? Are they useful, or are they simply scaled up versions of other icons?
- [ ] Make sure (with a CI test or the like) that every icon can be properly styled.
    Some icons can't seem to be styled because they use internal styles.
- [ ] Revisit they way `twotone` icons are handled.
     currently, we set a class on the secondary elements of `twotone` icons, but maybe there is a better solution.

**Comment by martijnarts** [comment]
> Writing a cron job that periodically updates icon libraries.

An alternative, slightly more complex but a bit more efficient, could be a CI job that rebuilds the libraries which could get triggered by [renovate](https://github.com/renovatebot/renovate) PRs based on new releases of the source icon libs.

**Comment by carloskiki** [comment]
> An alternative, slightly more complex but a bit more efficient, could be a CI job that rebuilds the libraries which could get triggered by [renovate](https://github.com/renovatebot/renovate) PRs based on new releases of the source icon libs.

Great idea!
